[package]
name = "sciimg"
version = "0.1.0"
authors = ["Kevin M. Gill <kmsmgill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
imageproc = "0.22.0"
clap = "2.33.3"
memmap = "0.7.0"
chrono = "0.4.19"
fastblur = "0.1.1"
rayon = "1.5.1"
lab = "0.11.0"